SET XACT_ABORT ON;

CREATE TABLE [dbo].[user] (
    [id] INT IDENTITY(1,1) PRIMARY KEY,
    [username] NVARCHAR(80) NOT NULL UNIQUE,
    [password] NVARCHAR(255) NOT NULL,
    [role] NVARCHAR(50) DEFAULT N'user',
    [created_at] DATETIME2 DEFAULT SYSUTCDATETIME(),
    [updated_at] DATETIME2 DEFAULT SYSUTCDATETIME()
);

SELECT COLUMN_NAME AS ColumnName, DATA_TYPE AS DataType
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = N'dbo'
  AND TABLE_NAME = N'user'
ORDER BY ORDINAL_POSITION;